// Regenerates web/icons.ts from the free Iconsax set (npm `iconsax`, MIT) so the app ships only the icons it uses.
// Usage: node scripts/icons.mjs  — add a name to NAMES, rerun, commit the generated file.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const dist = path.join(root, 'node_modules', 'iconsax', 'dist');
const STYLE = 'bold';
const NAMES = [
  'add', 'edit-2', 'trash', 'play', 'timer', 'clock', 'music', 'volume-high', 'volume-slash', 'maximize-4',
  'close-circle', 'tick-circle', 'logout-02', 'login-02', 'arrow-left-02', 'arrow-up-01', 'arrow-down-01',
  'people', 'crown', 'cup', 'medal-star', 'lamp-on', 'scan', 'refresh-circle', 'save-2', 'minus-circle', 'danger', 'flash', 'user', 'home-2',
];

const manifest = JSON.parse(fs.readFileSync(path.join(dist, 'manifest.json'), 'utf8'));
const categories = new Map();
const svgs = {};
for (const name of NAMES) {
  const entry = manifest[name];
  if (!entry?.styles.includes(STYLE)) throw new Error(`Iconsax has no ${STYLE} "${name}"`);
  if (!categories.has(entry.category)) categories.set(entry.category, JSON.parse(fs.readFileSync(path.join(dist, 'data', entry.category + '.json'), 'utf8')));
  const body = categories.get(entry.category)[name][STYLE]
    .replace(/<defs>.*?<\/defs>/s, '')
    .replace(/<\/?g[^>]*>/g, '')
    .replace(/^.*?<svg[^>]*>|<\/svg>\s*$/gs, '')
    .replace(/"white"/g, '"currentColor"')
    .replace(/\s+/g, ' ')
    .replace(/> </g, '><')
    .trim();
  svgs[name] = body;
}

const out = `// Generated by scripts/icons.mjs from Iconsax (${STYLE}). Do not edit by hand.
const PATHS = ${JSON.stringify(svgs, null, 1)} as const;
export type IconName = keyof typeof PATHS;
export const ICON_NAMES = Object.keys(PATHS) as IconName[];
export const icon = (name: IconName) => \`<svg class="i" viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false">\${PATHS[name]}</svg>\`;
`;
fs.writeFileSync(path.join(root, 'web', 'icons.ts'), out);
console.log(`web/icons.ts: ${NAMES.length} icons, ${out.length} bytes`);
