import './style.css';
import QRCode from 'qrcode';
import { enableSound, cue, beat } from './sound';
import { fitStage, stopStageFit } from './stage';
import type { Quiz, Question, RoomView } from '../src/shared';
const app = document.querySelector<HTMLDivElement>('#app')!;
const escape = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const letters = ['A', 'B', 'C', 'D'];
let user: { name: string; email: string } | null = null;
let draft: Quiz | null = null, editIndex = 0, socket: WebSocket | null = null, state: RoomView | null = null, socketKey = '', reconnect: ReturnType<typeof setTimeout> | null = null, attempts = 0, disconnected = false, offset = 0, submitting = false;
// Each page load needs a user gesture to unlock browser audio.
let muted = true, lastBeat = -1, lastCue = '';
let qrCache: { url: string; data: string } | null = null, roomRoute = '', renderVersion = 0;
function toast(message: string) { document.querySelector('.toast')?.remove(); const el = document.createElement('div'); el.className = 'toast'; el.setAttribute('role', 'alert'); el.textContent = message; document.body.append(el); setTimeout(() => el.remove(), 5000); }
async function api<T>(path: string, method = 'GET', body?: unknown): Promise<T> {
  const response = await fetch(path, { method, credentials: 'same-origin', headers: body === undefined ? {} : { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) });
  const data = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(data.error || 'เกิดข้อผิดพลาด'); return data;
}
function header() { return `<header class="header"><a href="/" data-nav class="brand"><img src="/logo.png" alt="PiN TO!"><div><strong>PiN TO<span>! / QUIZ</span></strong><small>PLAY · THINK · WIN</small></div></a><div class="controls">${user ? `<span>${escape(user.name)}</span><button data-action="library">คลัง Quiz</button><button data-action="logout">ออกจากระบบ</button>` : '<a href="/login" data-nav>สำหรับผู้จัดเกม</a>'}</div></header>`; }
function shell(content: string) { stopStageFit(); document.body.dataset.view = location.pathname.startsWith('/host') ? 'host' : 'site'; app.innerHTML = `<div class="shell">${header()}<main class="main">${content}</main></div>`; }
function playerShell(content: string) { stopStageFit(); document.body.dataset.view = 'player'; app.innerHTML = `<div class="player-shell"><header class="player-header"><strong>PiN TO! / PLAY</strong><button data-action="sound" aria-pressed="${!muted}">${muted ? 'เปิดเสียง' : 'ปิดเสียง'}</button></header>${disconnected ? '<div class="connection" role="status">กำลังเชื่อมต่อใหม่…</div>' : ''}<main class="player-main">${content}</main></div>`; }
function go(path: string) { history.pushState(null, '', path); void route().catch(e => toast(e.message)); }
function stopSocket() { socketKey = ''; socket?.close(); socket = null; if (reconnect) clearTimeout(reconnect); reconnect = null; state = null; attempts = 0; disconnected = false; lastCue = ''; delete document.body.dataset.phase; }
async function needUser() { if (!user) { try { user = await api('/api/me'); } catch { go('/login?return=' + encodeURIComponent(location.pathname)); return false; } } return true; }
function makeQuestion(): Question { return { id: crypto.randomUUID(), text: '', options: ['', '', '', ''], correct: 0, explanation: '', duration: 20, maxScore: 1000 }; }
async function route() {
  const path = location.pathname;
  const room = path.match(/^\/(host|play)\/(\d{6})$/);
  if (room) { const [, role, pin] = room; if (roomRoute !== path) { stopSocket(); roomRoute = path; } if (role === 'host' && !await needUser()) return; if (role === 'host') { shell('<div class="loading">กำลังเปิดห้อง…</div>'); connect(pin, true); } else { playerShell('<div class="loading">กำลังเปิดห้อง…</div>'); try { const info = await api<{ title: string; phase: string }>('/api/rooms/' + pin); const joined = sessionStorage.getItem('pinto-joined-' + pin); if (joined) connect(pin, false); else joinForm(pin, info.title); } catch (e) { playerShell(`<h1>เข้าห้องไม่ได้</h1><p>${escape((e as Error).message)}</p><button class="primary" data-action="home">กลับหน้าแรก</button>`); } } return; }
  stopSocket(); roomRoute = '';
  if (path === '/login') { if (await api('/api/me').then(u => { user = u as typeof user; return true; }).catch(() => false)) { go('/admin'); return; } shell(`<div class="loginlayout"><div class="intro"><div class="kicker">HOST ACCESS</div><h1>จัดควิซของคุณ<br>ให้เป็นเรื่องสนุก</h1><p>เข้าสู่ระบบเพื่อสร้าง Quiz และเปิดห้องเล่น</p><div class="hero-mascot"><span class="float-badge badge-one">⚡ THINK FAST!</span><img src="/mascot-v2.webp" alt="มาสคอต PiN TO!"><span class="float-badge badge-two">✦ LET’S PLAY</span></div></div><form id="login-form" class="formpanel"><h2>เข้าสู่ระบบผู้จัด</h2><div class="field"><label for="email">อีเมล</label><input id="email" name="email" type="email" autocomplete="username" required maxlength="254"></div><div class="field"><label for="password">รหัสผ่าน</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="128"></div><button class="primary" type="submit">เข้าสู่ระบบ</button><p class="small">สำหรับบัญชีที่ได้รับอนุญาตเท่านั้น<br>การสมัครใช้งานยังไม่เปิดให้บริการ</p></form></div>`); return; }
  if (path === '/admin') { if (!await needUser()) return; shell('<div class="loading">กำลังโหลด Quiz…</div>'); const quizzes = await api<Quiz[]>('/api/quizzes'); shell(`<div class="headrow"><div><div class="kicker">YOUR QUIZ COLLECTION</div><h1>เลือกชุด แล้วเปิดเกม</h1><p>Quiz ของคุณ / ${quizzes.length} ชุด</p></div><button class="primary" data-action="new">＋ สร้าง Quiz</button></div><div class="arena-banner"><div><span class="live-label">● YOUR PLAYGROUND</span><h2>เปลี่ยนทุกคำถาม<br>ให้เป็นโมเมนต์สนุก!</h2><p>สแกนเข้าห้อง · คิดให้ไว · พุ่งขึ้นอันดับ</p><div class="featurechips"><span>⚡ ตอบเร็ว ได้แต้มเยอะ</span><span>♫ จังหวะเร้าใจ</span><span>✦ เฉลยพร้อมกัน</span></div></div><div class="mascot-orbit"><img src="/mascot-v2.webp" alt="มาสคอต PiN TO! รุ่นใหม่"></div></div>${quizzes.length ? `<div class="collection">${quizzes.map((q, i) => `<article class="quizcard"><div class="cover"><img src="/mascot-v2.webp" alt="" class="card-mascot"><span>QUIZ / ${String(i + 1).padStart(2, '0')}</span><strong>คิดไว<br>ได้แต้ม!</strong></div><div class="qdetails"><h2>${escape(q.title)}</h2><p>${q.questions.length} คำถาม · ${q.music ? 'เปิด' : 'ปิด'}เสียงนับถอยหลัง</p><div class="controls"><button data-action="edit" data-id="${q.id}">แก้ไข</button><button class="primary" data-action="host" data-id="${q.id}">เปิดห้อง</button><button class="quiet danger" data-action="delete" data-id="${q.id}" aria-label="ลบ Quiz ${escape(q.title)}">ลบ</button></div></div></article>`).join('')}</div>` : '<div class="empty"><img src="/mascot-v2.webp" alt="PiN TO! พร้อมเล่น"><h2>เริ่มจาก Quiz ชุดแรก</h2><p>เพิ่มคำถาม กำหนดคำตอบ แล้วเปิดห้องให้ทุกคนเข้าร่วม</p><button class="primary" data-action="new">＋ สร้าง Quiz</button></div>'}<div class="footer"><span>ตอบถูก ยิ่งเร็ว ยิ่งได้คะแนน</span><span>เฉพาะ Quiz ของบัญชีคุณ</span></div>`); return; }
  if (path === '/admin/new' || /^\/admin\/quiz\/[a-f0-9-]{36}$/.test(path)) { if (!await needUser()) return; draft = path === '/admin/new' ? { id: '', title: '', music: true, questions: [makeQuestion()], updatedAt: 0 } : await api<Quiz>('/api/quizzes/' + path.split('/').pop()); editIndex = 0; renderEditor(); return; }
  shell(`<div class="loginlayout"><div class="intro"><div class="kicker">PiN TO! QUIZ ARENA</div><h1>คิดไว กดไว<br>ได้แต้มเต็ม!</h1><p>เข้าห้องด้วย PIN หรือสแกน QR บนจอผู้จัด</p><div class="hero-mascot"><span class="float-badge badge-one">⚡ THINK FAST!</span><img src="/mascot-v2.webp" alt="มาสคอต PiN TO!"><span class="float-badge badge-two">✦ LET’S PLAY</span></div></div><form id="pin-form" class="formpanel"><div class="kicker">JOIN THE FUN</div><h2>เข้าร่วมเกม</h2><div class="field"><label for="pin">PIN ห้อง 6 หลัก</label><input id="pin" name="pin" inputmode="numeric" pattern="[0-9]{6}" minlength="6" maxlength="6" required placeholder="482916" autocomplete="off"></div><button class="primary" type="submit">เข้าห้อง</button><p class="small">ผู้เล่นไม่ต้องสมัครสมาชิก</p></form></div>`);
}
function renderEditor() { if (!draft) return; const q = draft.questions[editIndex]; shell(`<div class="headrow"><div><div class="kicker">QUIZ BUILDER</div><h1>${draft.id ? 'แก้ไข Quiz' : 'สร้าง Quiz ใหม่'}</h1></div><div class="controls"><button data-action="library">กลับคลัง Quiz</button><button class="primary" data-action="save">บันทึก Quiz</button></div></div><div class="editorgrid"><aside class="questionnav">${draft.questions.map((_, i) => `<button class="${i === editIndex ? 'active' : ''}" data-action="edit-question" data-index="${i}">ข้อ ${String(i + 1).padStart(2, '0')}</button>`).join('')}<button data-action="add-question">＋ เพิ่มคำถาม</button></aside><div><div class="field"><label for="quiz-title">ชื่อ Quiz</label><input id="quiz-title" value="${escape(draft.title)}" maxlength="120" placeholder="ความรู้รอบตัวฉบับไว"></div><div class="field"><label for="question-text">คำถาม</label><textarea id="question-text" maxlength="500" placeholder="พิมพ์คำถาม…">${escape(q.text)}</textarea></div><div class="editchoices">${q.options.map((a, i) => `<label class="editchoice"><input type="radio" name="correct" value="${i}" ${q.correct === i ? 'checked' : ''} aria-label="${letters[i]} เป็นคำตอบที่ถูก"><span>${letters[i]}</span><input type="text" data-option="${i}" value="${escape(a)}" maxlength="200" aria-label="คำตอบ ${letters[i]}" placeholder="ตัวเลือก ${letters[i]}"></label>`).join('')}</div><p class="small" style="margin-bottom:20px">เลือกวงกลมหน้าคำตอบที่ถูกต้อง</p><div class="field"><label for="explanation">คำอธิบายสำหรับหน้าเฉลย</label><textarea id="explanation" maxlength="1500" placeholder="อธิบายว่าทำไมข้อนี้จึงถูก…">${escape(q.explanation)}</textarea></div><div class="settings"><div><label for="duration">เวลาตอบ</label><select id="duration">${[10, 15, 20, 30, 60, 90, 120].map(n => `<option value="${n}" ${q.duration === n ? 'selected' : ''}>${n} วินาที</option>`).join('')}</select></div><div><label for="max-score">คะแนนสูงสุด</label><select id="max-score"><option value="1000" ${q.maxScore === 1000 ? 'selected' : ''}>1,000 คะแนน</option><option value="2000" ${q.maxScore === 2000 ? 'selected' : ''}>2,000 คะแนน</option></select></div></div><label class="check"><input id="music" type="checkbox" ${draft.music ? 'checked' : ''}>เปิดเสียงจังหวะนับถอยหลัง</label>${draft.questions.length > 1 ? '<button class="quiet danger" style="margin-top:20px" data-action="remove-question">ลบคำถามนี้</button>' : ''}</div></div>`); }
function syncDraft() { if (!draft) return; const q = draft.questions[editIndex]; const value = (id: string) => document.querySelector<HTMLInputElement>('#' + id)!.value; draft.title = value('quiz-title'); q.text = value('question-text'); q.explanation = value('explanation'); q.options = Array.from(document.querySelectorAll<HTMLInputElement>('[data-option]')).map(e => e.value); q.correct = Number(document.querySelector<HTMLInputElement>('[name="correct"]:checked')!.value); q.duration = Number(value('duration')); q.maxScore = Number(value('max-score')); draft.music = document.querySelector<HTMLInputElement>('#music')!.checked; }
function joinForm(pin: string, title: string) { playerShell(`<img class="mascot" src="/mascot-v2.webp" alt="PiN TO! ต้อนรับผู้เล่น"><h1>พร้อมแข่งหรือยัง?</h1><p style="text-align:center;margin-bottom:22px">${escape(title)} · PIN ${escape(pin)}</p><form id="join-form" data-pin="${pin}"><label for="player-name">ชื่อของคุณ</label><input id="player-name" name="name" maxlength="24" required autocomplete="nickname" placeholder="ตั้งชื่อก่อนเข้าเล่น" value="${escape(localStorage.getItem('pinto-name') || '')}"><button class="primary" type="submit">เข้าร่วมเกม</button></form>`); }
function connect(pin: string, host: boolean) {
  const key = `${host ? 'host' : 'player'}:${pin}`; if (socketKey === key && socket?.readyState === WebSocket.OPEN) { renderRoom(host); return; }
  socketKey = key; const ws = new WebSocket(`${location.protocol === 'https:' ? 'wss:' : 'ws:'}//${location.host}/api/rooms/${pin}/ws${host ? '?role=host' : ''}`); socket = ws;
  ws.onopen = () => { if (socket !== ws) return; attempts = 0; disconnected = false; if (state) renderRoom(host); };
  ws.onmessage = e => { if (socket !== ws || e.data === 'pong') return; try { const data = JSON.parse(e.data) as { type: string; state: RoomView; error: string }; if (data.type === 'error') { submitting = false; toast(data.error); if (state) renderRoom(host); return; } const next = data.state; if (!next) return; if (state?.question?.id !== next.question?.id) { lastBeat = -1; submitting = false; } state = next; offset = next.serverTime - Date.now(); submitting = next.me?.answered || false; renderRoom(host); } catch { toast('ข้อมูลจากห้องไม่ถูกต้อง'); } };
  ws.onclose = () => { if (socket !== ws || socketKey !== key) return; disconnected = true; if (state) renderRoom(host); attempts++; if (attempts > 8) { toast('เชื่อมต่อห้องไม่ได้ กรุณาเข้าห้องใหม่'); if (!host) { sessionStorage.removeItem('pinto-joined-' + pin); void api<{ title: string }>('/api/rooms/' + pin).then(i => joinForm(pin, i.title)).catch(e => playerShell(`<h1>ห้องสิ้นสุดแล้ว</h1><p>${escape(e.message)}</p><button class="primary" data-action="home">กลับหน้าแรก</button>`)); } return; } reconnect = setTimeout(() => { if (socketKey === key) connect(pin, host); }, Math.min(1000 * 2 ** (attempts - 1), 15000)); };
  ws.onerror = () => ws.close();
}
function ranks(s: RoomView, limit = 10) { return s.players.slice(0, limit).map((p, i) => `<div class="rankrow"><strong>${String(i + 1).padStart(2, '0')}</strong><span>${escape(p.name)}${s.me?.id === p.id ? '<small>คุณ</small>' : ''}</span><strong>${p.score.toLocaleString()}</strong></div>`).join(''); }
function countdownView(s: RoomView) { return `<section class="ready-stage"><div class="kicker">GET READY / ข้อ ${s.questionIndex + 1} จาก ${s.questionCount}</div><h1>เตรียมตัวให้พร้อม!</h1><div class="ready-orbit"><img src="/mascot-v2.webp" alt="PiN TO! พร้อมลุย"><div class="countdown-digit" data-countdown role="timer" aria-label="นับถอยหลังก่อนเริ่ม"></div></div><p>ตอบถูก + ตอบไว = แต้มพุ่ง ⚡</p><div class="ready-dots"><i></i><i></i><i></i></div></section>`; }
function timerView() { return `<div class="clock-wrap"><div class="timer" data-timer role="timer" aria-label="เวลาที่เหลือ"><div><span data-seconds></span><small>วินาที</small></div></div><div class="time-track"><div data-timebar></div></div><div class="speed-hint">⚡ ตอบถูกตอนนี้ <strong data-potential></strong> คะแนนโดยประมาณ</div></div>`; }
function confetti() { return `<div class="confetti" aria-hidden="true">${Array.from({ length: 28 }, (_, i) => `<i style="--x:${(i * 37) % 100}%;--delay:${(i % 7) * .11}s;--turn:${i * 41}deg;--color:${['#25c76a','#f9cf65','#7bd8e2','#f997ac'][i % 4]}"></i>`).join('')}</div>`; }
function podium(s: RoomView) { return `<div class="podium">${[1, 0, 2].filter(i => s.players[i]).map(i => `<div class="podium-place place-${i + 1}"><span class="medal">${['♛', '★', '✦'][i]}</span><h2>${escape(s.players[i].name)}</h2><p>${s.players[i].score.toLocaleString()} คะแนน</p><div class="podium-step">${i + 1}</div></div>`).join('')}</div>`; }
function renderRoom(host: boolean) { if (!state) return; const s = state, q = s.question; renderVersion++; document.body.dataset.phase = s.phase;
  if (host) {
    let body = `<div class="headrow"><div><div class="kicker">HOST / ${escape(s.pin)}</div><h1>${escape(s.title)}</h1></div><div class="controls"><button data-action="sound" aria-pressed="${!muted}">${muted ? 'เปิดเสียง' : 'ปิดเสียง'}</button><button data-action="fullscreen">เต็มจอ</button>${s.phase !== 'closed' ? '<button class="quiet" data-command="close">ปิดห้อง</button>' : ''}</div></div>`;
    if (s.phase === 'lobby') body += `<div class="lobbygrid"><div class="pinpanel"><p>PIN เข้าห้อง</p><div class="pin">${s.pin.slice(0, 3)} ${s.pin.slice(3)}</div><div class="joinqr"><img id="join-qr" alt="QR Code สำหรับเข้าห้อง ${s.pin}" hidden><p>สแกน QR เพื่อตั้งชื่อ<br>ไม่ต้องกรอก PIN<br><a href="/play/${s.pin}" target="_blank" rel="noopener">เปิดหน้าผู้เล่น</a></p></div><div class="lobbymascot"><img src="/mascot-v2.webp" alt="มาสคอต PiN TO!"><p>PiN TO! พร้อมแล้ว<br>คุณล่ะ พร้อมไหม?</p></div></div><div class="roster"><h2>ผู้เล่นพร้อมแล้ว / ${s.playerCount}</h2><div class="names">${s.players.map(p => `<span>${escape(p.name)}</span>`).join('')}</div>${!s.playerCount ? '<p>รอผู้เล่นสแกน QR หรือกรอก PIN</p>' : ''}<button class="primary" data-command="start" style="width:100%;margin-top:20px" ${s.playerCount ? '' : 'disabled'}>เริ่มเกม</button><p class="small" style="margin-top:14px">สูงสุด 300 คนต่อห้อง</p></div></div>`;
    else if (s.phase === 'countdown') body += countdownView(s);
    else if (s.phase === 'question' && q) body += `<div class="gameinfo"><span>ข้อ ${s.questionIndex + 1} / ${s.questionCount}</span><span>ตอบแล้ว ${s.answeredCount} / ${s.playerCount}</span></div>${timerView()}<h2 class="stage-question">${escape(q.text)}</h2><div class="stageanswers">${q.options.map((a, i) => `<div class="stageanswer answer-${i}"><span class="letter">${letters[i]}</span><span>${escape(a)}</span></div>`).join('')}</div><div class="hostbottom"><p>เฉลยเมื่อทุกคนตอบครบ หรือหมดเวลา</p><button class="primary" data-command="reveal">ปิดรับคำตอบและเฉลย</button></div>`;
    else if (s.phase === 'reveal' && q) body += `${confetti()}<div class="kicker reveal-kicker">ANSWER REVEAL / ข้อ ${s.questionIndex + 1}</div><div class="reveal-layout"><section class="reveal-story"><div class="revealhero"><div><div class="correctpill">✓ คำตอบที่ถูกต้อง</div><h1 class="revealtitle">${letters[q.correct!]} · ${escape(q.options[q.correct!])}</h1><p>${escape(q.text)}</p></div><img src="/mascot-v2.webp" alt="PiN TO! ช่วยเฉลย"></div>${q.explanation ? `<div class="explanation"><h2>ทำไมข้อนี้ถึงถูก?</h2><p>${escape(q.explanation)}</p></div>` : ''}</section><section class="reveal-responses"><div class="stageanswers">${q.options.map((a, i) => `<div class="stageanswer answer-${i} ${i === q.correct ? 'correct' : ''}"><span class="letter">${letters[i]}</span><span>${escape(a)}</span>${i === q.correct ? '<span class="caption">✓ ถูกต้อง</span>' : ''}</div>`).join('')}</div><div class="distribution" aria-label="จำนวนผู้เล่นที่เลือกแต่ละคำตอบ">${q.options.map((_, i) => `<div class="distrow"><strong>${letters[i]}</strong><div class="track"><div class="bar ${i === q.correct ? 'correct' : ''}" style="width:${s.answeredCount ? (s.distribution![i] / s.answeredCount * 100) : 0}%"></div></div><span>${s.distribution![i]} คน</span></div>`).join('')}</div></section></div><div class="hostbottom"><p>ตอบแล้ว ${s.answeredCount} / ${s.playerCount}</p><div class="controls"><button data-command="leaderboard">ดูอันดับ</button><button class="primary" data-command="next">${s.questionIndex + 1 === s.questionCount ? 'จบเกม' : 'ข้อถัดไป'}</button></div></div>`;
    else if (s.phase === 'leaderboard' || s.phase === 'finished') body += `${s.phase === 'finished' ? confetti() : ''}<div class="headrow"><div><div class="kicker">${s.phase === 'finished' ? 'FINAL RESULTS' : 'LEADERBOARD'}</div><h1>${s.phase === 'finished' ? 'แชมป์ของเกมนี้!' : 'ใครไว ใครนำ'}</h1></div><img src="/mascot-v2.webp" alt="PiN TO! ฉลองผลคะแนน" style="width:110px;height:120px;object-fit:contain"></div><div class="standings-layout">${podium(s)}<div>${ranks(s, 5)}</div></div><div class="hostbottom"><p>${s.playerCount} ผู้เล่น · ${s.questionCount} คำถาม</p>${s.phase === 'finished' ? '<button class="primary" data-action="library">กลับคลัง Quiz</button>' : `<button class="primary" data-command="next">${s.questionIndex + 1 === s.questionCount ? 'จบเกม' : 'ข้อถัดไป'}</button>`}</div>`;
    else body += '<div class="empty"><h1>ห้องนี้ปิดแล้ว</h1><button class="primary" data-action="library">กลับคลัง Quiz</button></div>';
    const content = (disconnected ? '<div class="connection">กำลังเชื่อมต่อใหม่…</div>' : '') + body;
    const stage = ['countdown', 'question', 'reveal', 'leaderboard', 'finished'].includes(s.phase);
    shell(stage ? `<div class="stage-viewport"><div class="stage-canvas">${content}</div></div>` : content);
    if (stage) fitStage();
    if (s.phase === 'lobby') void renderQR(s.pin);
  } else {
    const info = `<div class="gameinfo"><span>${escape(s.me?.name)}</span><span>PIN ${s.pin}</span></div>`;
    let body = info;
    if (s.phase === 'lobby') body += `<img class="mascot" src="/mascot-v2.webp" alt="PiN TO! รอเริ่มเกม"><h1>เข้าห้องแล้ว!</h1><p style="text-align:center">${escape(s.title)}<br>รอผู้จัดเริ่มเกม · ${s.playerCount} คนพร้อมเล่น</p>`;
    else if (s.phase === 'countdown') body += countdownView(s);
    else if (s.phase === 'question' && q) body += `<div class="gameinfo"><span>ข้อ ${s.questionIndex + 1} / ${s.questionCount}</span><span>${s.me?.score.toLocaleString()} คะแนน</span></div>${timerView()}<h2>${escape(q.text)}</h2><div class="gameanswers">${q.options.map((a, i) => `<button class="answer-${i} ${s.me?.choice === i ? 'selected' : ''}" data-answer="${i}" ${s.me?.answered || submitting || disconnected ? 'disabled' : ''}><b>${letters[i]}</b>${escape(a)}</button>`).join('')}</div>${s.me?.answered || submitting ? '<p class="waiting" style="text-align:center" role="status"><span class="sent-check">✓</span>ส่งคำตอบแล้ว!<br>รอดูเฉลยพร้อมกัน</p>' : '<p class="small" style="text-align:center">ตอบได้ครั้งเดียว ยิ่งเร็ว ยิ่งได้คะแนน</p>'}`;
    else if (s.phase === 'reveal' && q) { const correct = s.me?.choice === q.correct; body += `${correct && s.me?.answered ? confetti() : ''}<div class="result-stamp">${correct && s.me?.answered ? '✦' : '♡'}</div><h1>${s.me?.answered ? correct ? 'ตอบถูกแล้ว!' : 'ยังไม่ถูก ลองข้อหน้า!' : 'หมดเวลาแล้ว'}</h1><div class="answer-correct"><span>✓ คำตอบที่ถูกต้อง</span><h2 style="text-align:left;margin:8px 0 0">${letters[q.correct!]} · ${escape(q.options[q.correct!])}</h2></div>${s.me?.answered && !correct ? `<p>คุณเลือก ${letters[s.me.choice!]} · ${escape(q.options[s.me.choice!])}</p>` : ''}<div class="resultpoints"><strong>+${(s.me?.points || 0).toLocaleString()}</strong><span>${s.me?.answered ? `ตอบใน ${((s.me.elapsed || 0) / 1000).toFixed(1)} วินาที` : 'ไม่ได้ส่งคำตอบ'}</span></div>${q.explanation ? `<div class="explanation"><h2>เฉลยจาก PiN TO!</h2><p>${escape(q.explanation)}</p></div>` : ''}<p style="text-align:center">รวม ${s.me?.score.toLocaleString()} คะแนน<br>รอผู้จัดไปข้อถัดไป</p>`; }
    else if (s.phase === 'leaderboard' || s.phase === 'finished') { const rank = s.players.findIndex(p => p.id === s.me?.id) + 1; body += `<img class="mascot" src="/mascot-v2.webp" alt="PiN TO! ฉลองคะแนน"><h1>${s.phase === 'finished' ? 'จบเกมแล้ว!' : 'อันดับของคุณ'}</h1><div class="resultpoints"><strong>#${rank}</strong><span>${s.me?.score.toLocaleString()} คะแนน / ${s.playerCount} ผู้เล่น</span></div>${ranks(s, 3)}<p style="text-align:center;margin-top:22px">${s.phase === 'finished' ? 'ขอบคุณที่เล่นด้วยกัน!' : 'รอผู้จัดไปข้อถัดไป'}</p>${s.phase === 'finished' ? '<button class="primary" data-action="home">กลับหน้าแรก</button>' : ''}`; }
    else body += '<h1>ห้องนี้ปิดแล้ว</h1><button class="primary" data-action="home">กลับหน้าแรก</button>';
    playerShell(body);
  }
  const cueKey = `${s.pin}:${s.phase}:${s.questionIndex}`;
  if (cueKey !== lastCue) {
    lastCue = cueKey; lastBeat = -1;
    if (!muted && s.music) {
      if (s.phase === 'question') cue('go');
      if (s.phase === 'reveal') cue(host || s.me?.choice === q?.correct && s.me?.answered ? 'correct' : 'wrong');
      if (s.phase === 'finished') cue('finish');
    }
  }
  updateTimer();
}
async function renderQR(pin: string) { const version = renderVersion; const url = location.origin + '/play/' + pin; if (!qrCache || qrCache.url !== url) qrCache = { url, data: await QRCode.toDataURL(url, { width: 320, margin: 2, errorCorrectionLevel: 'M', color: { dark: '#1b1e50', light: '#fffdeb' } }) }; if (renderVersion !== version) return; const img = document.querySelector<HTMLImageElement>('#join-qr'); if (img) { img.src = qrCache.data; img.hidden = false; } }
function updateTimer() {
  if (!state || !['countdown', 'question'].includes(state.phase)) return;
  const remaining = Math.max(0, state.deadline - (Date.now() + offset)), sec = Math.ceil(remaining / 1000);
  if (state.phase === 'countdown') {
    const digit = document.querySelector<HTMLElement>('[data-countdown]');
    if (digit && digit.textContent !== String(sec)) { digit.textContent = sec > 0 ? String(sec) : 'GO!'; digit.classList.remove('pop'); void digit.offsetWidth; digit.classList.add('pop'); }
  } else {
    document.querySelectorAll('[data-seconds]').forEach(e => e.textContent = String(sec));
    const ratio = Math.min(1, remaining / ((state.question?.duration || 20) * 1000));
    document.querySelectorAll<HTMLElement>('[data-timer]').forEach(e => { e.classList.toggle('urgent', sec <= 5); e.style.setProperty('--progress', `${ratio * 360}deg`); });
    document.querySelectorAll<HTMLElement>('[data-timebar]').forEach(e => { e.style.width = `${ratio * 100}%`; e.classList.toggle('urgent', sec <= 5); });
    document.querySelectorAll('[data-potential]').forEach(e => e.textContent = Math.round((state!.question?.maxScore || 1000) * (.5 + .5 * ratio)).toLocaleString());
    // Freeze input when the server deadline passes, even while the reveal message is in transit.
    if (!remaining) document.querySelectorAll<HTMLButtonElement>('[data-answer]').forEach(e => e.disabled = true);
  }
  if (sec !== lastBeat) { lastBeat = sec; if (!muted && state.music && sec > 0) beat(sec, state.phase === 'countdown'); }
}
setInterval(updateTimer, 200);
setInterval(() => { if (socket?.readyState === WebSocket.OPEN) socket.send('ping'); }, 25000);
app.addEventListener('click', e => { const target = (e.target as HTMLElement).closest<HTMLElement>('button, a[data-nav]'); if (!target) return; if (target instanceof HTMLAnchorElement) { e.preventDefault(); go(target.pathname); return; } void (async () => {
  const action = target.dataset.action;
  if (action === 'home') go('/'); if (action === 'library') go('/admin'); if (action === 'new') go('/admin/new'); if (action === 'edit') go('/admin/quiz/' + target.dataset.id);
  if (action === 'logout') { await api('/api/logout', 'POST'); user = null; go('/login'); }
  if (action === 'save' && draft) { syncDraft(); target.setAttribute('disabled', ''); await api<Quiz>('/api/quizzes' + (draft.id ? '/' + draft.id : ''), draft.id ? 'PUT' : 'POST', draft); toast('บันทึก Quiz แล้ว'); go('/admin'); }
  if (action === 'delete' && confirm('ลบ Quiz นี้หรือไม่?')) { await api('/api/quizzes/' + target.dataset.id, 'DELETE'); await route(); }
  if (action === 'host') { target.setAttribute('disabled', ''); const room = await api<{ pin: string }>('/api/rooms', 'POST', { quizId: target.dataset.id }); go('/host/' + room.pin); }
  if (action === 'add-question' && draft) { syncDraft(); if (draft.questions.length >= 100) throw new Error('เพิ่มได้สูงสุด 100 คำถาม'); draft.questions.push(makeQuestion()); editIndex = draft.questions.length - 1; renderEditor(); }
  if (action === 'edit-question') { syncDraft(); editIndex = Number(target.dataset.index); renderEditor(); }
  if (action === 'remove-question' && draft && confirm('ลบคำถามนี้หรือไม่?')) { syncDraft(); draft.questions.splice(editIndex, 1); editIndex = Math.min(editIndex, draft.questions.length - 1); renderEditor(); }
  if (action === 'sound') { if (muted) { await enableSound(); muted = false; cue('ready'); } else muted = true; lastBeat = -1; if (state) renderRoom(location.pathname.startsWith('/host')); else { target.textContent = muted ? 'เปิดเสียง' : 'ปิดเสียง'; target.setAttribute('aria-pressed', String(!muted)); } }
  if (action === 'fullscreen') { if (document.fullscreenElement) await document.exitFullscreen(); else await app.requestFullscreen(); }
  if (target.dataset.command && state) { if (target.dataset.command === 'close' && !confirm('ปิดห้องและหยุดเกมนี้หรือไม่?')) return; target.setAttribute('disabled', ''); await api('/api/rooms/' + state.pin + '/command', 'POST', { command: target.dataset.command }); }
  if (target.dataset.answer !== undefined && state?.question && !state.me?.answered && !submitting) { if (!socket || socket.readyState !== WebSocket.OPEN) throw new Error('กำลังเชื่อมต่อ กรุณารอสักครู่'); submitting = true; if (!muted && state.music) cue('answer'); socket.send(JSON.stringify({ type: 'answer', questionId: state.question.id, choice: Number(target.dataset.answer) })); renderRoom(false); }
})().catch(error => { target.removeAttribute('disabled'); toast((error as Error).message); }); });
app.addEventListener('submit', e => { e.preventDefault(); const form = e.target as HTMLFormElement; const button = form.querySelector<HTMLButtonElement>('button[type="submit"]')!; button.disabled = true; const fields = new FormData(form); void (async () => {
  if (form.id === 'login-form') { user = await api('/api/login', 'POST', { email: fields.get('email'), password: fields.get('password') }); const destination = new URLSearchParams(location.search).get('return') || '/admin'; go(/^\/host\/\d{6}$/.test(destination) ? destination : '/admin'); }
  if (form.id === 'pin-form') go('/play/' + String(fields.get('pin')));
  if (form.id === 'join-form') { const name = String(fields.get('name')).trim(), pin = form.dataset.pin!; await api('/api/rooms/' + pin + '/join', 'POST', { name }); localStorage.setItem('pinto-name', name); sessionStorage.setItem('pinto-joined-' + pin, '1'); connect(pin, false); }
})().catch(error => { button.disabled = false; toast((error as Error).message); }); });
window.addEventListener('popstate', () => void route().catch(e => toast(e.message)));
void route().catch(e => { shell(`<h1>เปิดหน้าไม่ได้</h1><p>${escape(e.message)}</p><button class="primary" data-action="home">กลับหน้าแรก</button>`); });
